spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      settings:
        web-allow-others : true
      path : /h2
      enabled : true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: pers.kamisaka.blog.entity